### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by MaybeThisIsRu** [TaylanTatli/add-to-miniflux#1]
The extension has a [GPL-3.0 license](http://www.gnu.org/licenses/gpl-3.0.html) on its [Mozilla extension page](https://addons.mozilla.org/en-US/firefox/addon/add-to-miniflux/).

Please consider [adding a `LICENSE` file](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) for this in the repository as well.

**Comment by TaylanTatli** [comment]
Ah sorry, you are right. I usually forgot that. Adding now. Thanks. :pray:
